require: rubocop-rails

inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  Exclude:
    - bin/*
    - db/migrate/*
    - db/schema.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/DuplicateMethods:
  Exclude:
    - app/models/setting.rb
