require:
  - rubocop-rails
  - rubocop-rspec

inherit_from:
- https://relaxed.ruby.style/rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.2
  Exclude:
    - bin/*
    - db/migrate/*
    - db/schema.rb
    - spec/rails_helper.rb
    - spec/spec_helper.rb

Style/FrozenStringLiteralComment:
  Enabled: false

Lint/DuplicateMethods:
  Exclude:
    - app/models/setting.rb

Lint/RaiseException:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/ExampleLength:
  Max: 25
