allowed_users:
  - jo.wojtowicz@gmail.com
  - przemyslawhaptas@gmail.com
  - paulina.materna@lunarlogic.io
  - thiswill@gmail.com
  - lesniakania@gmail.com
  - amjmigas@gmail.com
  - tomasz.gieres@lunarlogic.io
  - marek.ciupak@lunarlogic.io
  - artur.trzop@lunarlogic.io
  - pacyfik@gmail.com
