development:
  adapter: postgresql
  encoding: utf8
  database: railsgirls_development
  pool: 5

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: railsgirls_test
  pool: 5

production:
  adapter: postgresql
  encoding: utf8
  database: railsgirls_production
  pool: 5

cucumber:
  <<: *TEST
